-- IntraDoc Database Schema
-- Generated from DATABASE_SCHEMA.md
-- Database: intradoc

CREATE DATABASE IF NOT EXISTS intradoc;
USE intradoc;

-- TABLE 2: DIVISION
CREATE TABLE IF NOT EXISTS DIVISION (
    DIVISION_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE 7: SECTION
CREATE TABLE IF NOT EXISTS SECTION (
    SECTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DIVISION_ID INT NOT NULL,
    HEAD_ID INT NULL,
    FOREIGN KEY (DIVISION_ID) REFERENCES DIVISION(DIVISION_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE 11: USER
CREATE TABLE IF NOT EXISTS USER (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ID_NUMBER VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    PROFILE_IMAGE VARCHAR(500) NULL,
    SECTION_ID INT NOT NULL,
    FUNCTIONAL_ROLE ENUM('staff','section_unit_head','division_manager','regional_director','admin') NOT NULL DEFAULT 'staff',
    ORGANIZATIONAL_ROLE VARCHAR(100) NULL,
    STATUS ENUM('active','pending','suspended','inactive') NULL DEFAULT 'active',
    CREATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    APPROVED_AT TIMESTAMP NULL,
    APPROVED_BY INT NULL,
    FOREIGN KEY (SECTION_ID) REFERENCES SECTION(SECTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (APPROVED_BY) REFERENCES USER(USER_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- DOCUMENT_CATEGORY table (referenced by DOCUMENT but not in the 11 main tables)
CREATE TABLE IF NOT EXISTS DOCUMENT_CATEGORY (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE 3: DOCUMENT
CREATE TABLE IF NOT EXISTS DOCUMENT (
    DOCUMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NULL,
    FILE_LINK VARCHAR(500) NOT NULL,
    FINGERPRINT_HASH VARCHAR(256) NOT NULL,
    CATEGORY_ID INT NOT NULL,
    SECTION_ID INT NOT NULL,
    ASSIGNED_TO INT NULL,
    CREATED_BY INT NOT NULL,
    CREATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    FREQUENCY VARCHAR(100) NULL,
    TAGS TEXT NULL,
    FORWARDED_TO_REGIONAL TINYINT(1) NOT NULL DEFAULT 0,
    FORWARDED_BY INT NULL,
    FORWARDED_AT DATETIME NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES DOCUMENT_CATEGORY(CATEGORY_ID) ON DELETE CASCADE,
    FOREIGN KEY (SECTION_ID) REFERENCES SECTION(SECTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (ASSIGNED_TO) REFERENCES USER(USER_ID) ON DELETE SET NULL,
    FOREIGN KEY (CREATED_BY) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (FORWARDED_BY) REFERENCES USER(USER_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE 10: TASK (must be created before FEEDBACK and SYSTEM_NOTIFICATION)
CREATE TABLE IF NOT EXISTS TASK (
    TASK_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NULL,
    ASSIGNED_TO INT NOT NULL,
    ASSIGNED_BY INT NOT NULL,
    DUE_DATE DATETIME NOT NULL,
    PRIORITY ENUM('low','medium','high','urgent') NULL DEFAULT 'medium',
    STATUS ENUM('pending','in_progress','completed','cancelled') NULL DEFAULT 'pending',
    CATEGORY VARCHAR(100) NULL,
    TAGS TEXT NULL,
    REQUIRES_DOCUMENT TINYINT(1) NULL DEFAULT 0,
    SECTION_ID INT NULL,
    CREATED_AT DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LINKED_DOCUMENT_ID INT NULL,
    FOREIGN KEY (ASSIGNED_TO) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ASSIGNED_BY) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (SECTION_ID) REFERENCES SECTION(SECTION_ID) ON DELETE SET NULL,
    FOREIGN KEY (LINKED_DOCUMENT_ID) REFERENCES DOCUMENT(DOCUMENT_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE 8: STREAM_POST (must be created before FEEDBACK)
CREATE TABLE IF NOT EXISTS STREAM_POST (
    POST_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    MESSAGE TEXT NOT NULL,
    POSTED_BY INT NOT NULL,
    SECTION_ID INT NOT NULL,
    ATTACHMENT_LINK VARCHAR(500) NULL,
    ATTACHMENT_FILE_URL VARCHAR(512) NULL,
    ATTACHMENT_EXTERNAL_URL VARCHAR(512) NULL,
    CREATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (POSTED_BY) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (SECTION_ID) REFERENCES SECTION(SECTION_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE 1: ARCHIVE (must be created after DOCUMENT, TASK, and USER)
-- Note: Schema doc specifies BIGINT(20) for TASK_ID and VIEWER_USER_ID, but referenced columns are INT(11)
-- Using INT to match referenced table column types for foreign key compatibility
CREATE TABLE IF NOT EXISTS ARCHIVE (
    ARCHIVE_ID INT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT_ID INT NOT NULL,
    TASK_ID INT NULL,
    VIEWER_USER_ID INT NULL,
    CONTEXT ENUM('assigned_by','assigned_to','reports') NULL,
    ARCHIVED_BY INT NOT NULL,
    DATE_ARCHIVED TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT(DOCUMENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (TASK_ID) REFERENCES TASK(TASK_ID) ON DELETE SET NULL,
    FOREIGN KEY (VIEWER_USER_ID) REFERENCES USER(USER_ID) ON DELETE SET NULL,
    FOREIGN KEY (ARCHIVED_BY) REFERENCES USER(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE 4: DOCUMENT_APPROVAL
CREATE TABLE IF NOT EXISTS DOCUMENT_APPROVAL (
    APPROVAL_ID INT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    STATUS INT NOT NULL,
    REMARKS TEXT NULL,
    DATE_SUBMITTED TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    DATE_STATUS_CHANGED TIMESTAMP NULL,
    DATE_APPROVED TIMESTAMP NULL,
    FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT(DOCUMENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE 5: DOCUMENT_STATUS
CREATE TABLE IF NOT EXISTS DOCUMENT_STATUS (
    STATUS_ID INT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT_ID INT NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    REMARKS TEXT NULL,
    CREATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT(DOCUMENT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE 6: FEEDBACK (must be created after TASK, DOCUMENT, STREAM_POST, and USER)
CREATE TABLE IF NOT EXISTS FEEDBACK (
    FEEDBACK_ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_ID INT NOT NULL,
    RECIPIENT_ID INT NOT NULL,
    RELATED_TASK_ID INT NULL,
    RELATED_DOCUMENT_ID INT NULL,
    TYPE ENUM('positive','constructive','action_required','question') NOT NULL,
    CONTENT TEXT NOT NULL,
    IS_READ TINYINT(1) NULL DEFAULT 0,
    DOCUMENT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    POST_ID INT NULL,
    COMMENT TEXT NOT NULL,
    CREATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (RECIPIENT_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (RELATED_TASK_ID) REFERENCES TASK(TASK_ID) ON DELETE SET NULL,
    FOREIGN KEY (RELATED_DOCUMENT_ID) REFERENCES DOCUMENT(DOCUMENT_ID) ON DELETE SET NULL,
    FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT(DOCUMENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES STREAM_POST(POST_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE 9: SYSTEM_NOTIFICATION (must be created after TASK, DOCUMENT, and USER)
CREATE TABLE IF NOT EXISTS SYSTEM_NOTIFICATION (
    NOTIFICATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    MESSAGE TEXT NOT NULL,
    IS_READ TINYINT(1) NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    TYPE VARCHAR(50) NOT NULL DEFAULT 'general',
    TITLE VARCHAR(255) NOT NULL DEFAULT 'Notification',
    ACTION_URL VARCHAR(500) NULL,
    RELATED_TASK_ID INT NULL,
    RELATED_DOCUMENT_ID INT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (RELATED_TASK_ID) REFERENCES TASK(TASK_ID) ON DELETE CASCADE,
    FOREIGN KEY (RELATED_DOCUMENT_ID) REFERENCES DOCUMENT(DOCUMENT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert sample DIVISION data
INSERT INTO DIVISION (NAME, DESCRIPTION) VALUES
('Engineering and Operations', 'Engineering and operations division'),
('Administrative and Finance', 'Administrative and finance division');

-- Insert sample SECTION data
INSERT INTO SECTION (NAME, DIVISION_ID) VALUES
('Engineering', 1),
('Operations', 1),
('Institutional Development', 2),
('Finance', 2),
('Administrative', 2),
('Standalone Units', 2);

-- Add foreign key constraint for SECTION.HEAD_ID after USER table is created
ALTER TABLE SECTION 
ADD FOREIGN KEY (HEAD_ID) REFERENCES USER(USER_ID) ON DELETE SET NULL;

-- Insert admin user
-- Email: admin@nia.gov.ph
-- Password: admin123
INSERT INTO USER (NAME, ID_NUMBER, EMAIL, PASSWORD, SECTION_ID, FUNCTIONAL_ROLE, ORGANIZATIONAL_ROLE, STATUS, CREATED_AT) 
VALUES (
    'Admin Bootstrap',
    'ADM000',
    'admin@nia.gov.ph',
    '$2a$10$/yAtcNpM/BYEmos9pH1OAO7hjZl/RshRZEaWVEle/uxjzRPLcHaum',
    5,
    'admin',
    'Administrative',
    'active',
    NOW()
);

